# Generated by Django 5.0.3 on 2024-04-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_payments_rename_full_name_doctor_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bio',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='doctor',
            name='price',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='service',
            field=models.CharField(default='doctor', max_length=255),
        ),
    ]
