# Generated by Django 5.0.3 on 2024-04-09 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id_user_professional',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Doctor.patient'),
        ),
    ]
