# Generated by Django 5.0.3 on 2024-04-16 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0006_availability_availabilityoccurrence_event_timeslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='datetime',
            new_name='start_datetime',
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
