# Generated by Django 5.0.3 on 2024-04-17 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0007_rename_datetime_appointment_start_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabilityoccurrence',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='availabilityoccurrence',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='event',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='event',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='padding_for',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='document',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='photo',
        ),
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='evaluation/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='Doctor.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='AvailabilityOccurrence',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
